apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pdfserve
configMapGenerator:
- files:
  - manifests/configs/config.yaml
  name: pdfserve-config
- envs:
  - manifests/configs/env.conf
  name: pdfserve-config-env

resources:
- manifests/deploy.yaml
- manifests/svc.yaml
- manifests/ingress.yaml
- manifests/service-monitor.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: pdf.pdfapi.com
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pdf.pdfapi.com
  target:
    kind: Ingress
    name: pdfserve
