[project]
name = "pdfserve"
version = "0.0.2"
description = ""
authors = [{email="2t.antoine@gmail.com", name="ant31"}]
readme = "README.md"
packages = [{ include = "pdfserve" }]
include = []
requires-python = ">=3.12,<4"
dependencies = [
             "asyncio (>=3)",
             "pydantic",
             "click",
             "pyyaml",
             "sentry-sdk[fastapi]",
             "typing-extensions",
             "ant31box[s3]",
             "aiohttp-prometheus-exporter",
             "paramiko",
             "opticr @ git+https://github.com/lzayep/opticr@main",
             "aiohttp[speedups]",
             "aiohttp_requests",
             "fastapi[all]",
             "starlette-exporter",
             "pydantic-settings",
             "pypdf",
             "typer",
             "pillow",
             "rich",
             "fpdf2",
            "aiofiles",
            "aioshutil",
            "python-multipart",
            "types-fpdf2",
            "pillow-heif",
            "weasyprint (>=69.0,<70.0)"
]
[tool.poetry.scripts]
pdfserve = 'pdfserve.cmd.main:main'


[tool.poetry.group.dev.dependencies]
aioresponses = "*"
pyreadline = "*"
pylint-pydantic = "*"
black = "*"
ipython = "*"
pylint = "*"
pyre-check = "*"
types-requests = "*"
isort = "*"
pytest = "*"
coverage = "*"
pytest-cov = "*"
pytest-ordering = "*"
pytest-asyncio = "*"
pyright = "*"
pytest-aioresponses = "*"
ruff = "*"
bump-my-version = "^1.1.2"

[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
atomic = true
profile = "black"
line_length = 120
skip_gitignore = true

[tool.pytest]
testpaths = "tests/"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"



[tool.bumpversion]
current_version = "0.0.2"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
tag = true
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = true
commit = false
message = "Bump version: {current_version} → {new_version}"
commit_args = ""


[[tool.bumpversion.fiiles]]
filename = 'pdfserve/__init__.py'
search = "__version__ = \"{current_version}\""
replace = "__version__ = \"{new_version}\""
regex = true
